### ISSUE TITLE
Adding new layer, changing Origin and restricting AOI

### ISSUE THREAD

**Issue by LarsBoertjes** [Netherlands3D/twin#257]
Hello,

I have cloned the project and have three small questions, as I could not find the answers in the documentation:

1. How can I add a new base layer? I duplicated the "Wijknamen" layer in the StandardLayers to test it, but I do not see the duplicated layer when running the main scene.
2. I changed the origin in Configuration.cs (line 21) and ConfiguratorStarter.cs (line 25) to 842558, 447022, 0, but when I run the main scene, it still defaults to Amersfoort.
3. I would like to focus on the municipality of Delft for now. Is there a way to restrict my data to a specific AOI (Area of Interest)?

**Comment by mvriel** [comment]
Hi @LarsBoertjes,

I hope I will be able to answer your questions:

1. 

You are right, we haven't fully documented the process yet. Partly because we intend to improve that part in the near future. 

Your first step was correct, to duplicate a pre-existing layer, but that doesn't add it to the UI for it. To do this, you will need to amend the AddLayerPanel prefab with the correct UI elements, and you may want to remove the functionality listener so that it is always enabled

2. 

Ah yes, there is a known issue where the configuration is not read. We are working to fix that but that can take some time and we are even considering removing that part of the configuration in favor of the new 'projects' system where users can save and load a project file. 

You can address this either by creating a default project file by going to the desired location, click the 'save project' and include that in your build location at `StreamingAssets/ProjectTemplate.nl3d`. This should be automatically loaded. You could also change the "CurrentProject" asset's location instead, though I notice there is a `[SerializeField]` attribute missing on the cameraPosition private field.

3.

Add the moment we do not have a fencing feature, but you could easily add that by writing a MonoBehaviour script that -on update- checks the camera's position whether it falls within your fenced area. I do recommend using real-world coordinates to check, and get the real-world camera position by querying WorldTransform.Coordinate. 

The reason for this is because we use a 'Floating Origin' system and Unity coordinates will shift depending on where you are or even how far you have moved from the original position.

**Comment by mvriel** [comment]
Given our call and there has been no response in 2 weeks, I am going to assume you have all the information that you need and I will close this issue
